name = "zkita-ai-worker"
main = "worker.js"
compatibility_date = "2024-07-25"

[vars]
PROJECT_ID = "zkita-ai"

[[kv_namespaces]]
binding = "PUBLIC_JWK_CACHE_KV"
id = ""  # Will be filled after creation
